version: "3.9"
services:
    api:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            target: staging
        depends_on:
            - mariadb
            - redis
        restart: always
        ports:
            - 4000:4000

    mariadb:
        container_name: mariadb
        image: mariadb:10.10
        restart: always
        environment:
            - MARIADB_USER=milon27
            - MARIADB_PASSWORD=myPassWord
            - MARIADB_ROOT_PASSWORD=myPassWord
            - MARIADB_DATABASE=my_db
        ports:
            - 3307:3306
        volumes:
            - db_vol:/var/lib/mysql

    redis:
        container_name: redis
        image: redis:7.0.7-alpine
        restart: always
        volumes:
            - redis_vol:/data
        ports:
            - 6379:6379

volumes:
    db_vol: {}
    redis_vol: {}
