version: "3.9"
services:
    api:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            target: staging
        depends_on:
            - postgres
            - redis
        restart: always
        ports:
            - 4000:4000

    postgres:
        container_name: postgres
        image: postgres:12.12
        restart: always
        environment:
            - POSTGRES_USER=example
            - POSTGRES_PASSWORD=myPassWord
            - POSTGRES_DB=auth_db
        ports:
            - 5434:5432
        volumes:
            - db_vol:/var/lib/postgresql/data

    redis:
        container_name: redis
        image: redis:7.0.7-alpine
        restart: always
        volumes:
            - redis_vol:/data
        ports:
            - 6379:6379

volumes:
    db_vol: {}
    redis_vol: {}
