#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Increment the version number without creating a new commit and tag
npm run version:inc

# it will thorw error and stop commit if there is any linting error, it will ignore warning
npm run lint
